### ISSUE TITLE
Game Speed Improvements

### ISSUE THREAD

**Issue by cookies-xor-cream** [AlterNT/AI-Agent-Competition-Platform#31]
These queries are slow, replace `Database.queryGames` with a function to return a single game, and a function to return all games of a given user.

You can write a method in database and then replace the `Database.getQueryResult(...)` line with `Database.theFunctionsYouWrite`.
If that doesn't work just push it to a feature branch and assign this back to me, I'll take a look.

Please PR when you're done coz there's some cleanup I need to do regarding batched queries.

```ts
        // returns a single game
        // TODO: update docs
        app.get('/api/game', (req, res) => {
            const { gameId } = req.query;
            Database.getQueryResult(Database.queryGames, { id: gameId })
            .then((games) => {
                res.json({games});
            });
        });

        // return all games for a given user
        app.get('/api/agent-games', (req, res) => {
            const { agentId } = req.query;
            Database.getQueryResult(Database.queryGames, { agentScores: agentId })
            .then((games) => {
                res.json({games});
            });
        });
```

**Comment by kai-jinny** [comment]
i think these work ok? what are u using to quantify slow?

**Comment by cookies-xor-cream** [comment]
Query of the speed with regards to number of games.

Given N games these both run in O(N) time
